name: Heroku

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: sarveshwarge/test-on-heroku@v0.0.5
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          buildpack: ${{secrets.BUILDPACK}}
          branch: ${{secrets.BRANCH_TO_TEST}}
          dontuseforce: false
          usedocker: true
          appdir: ""
          docker_heroku_process_type: "web" 
